name = "email-worker"
main = "src/worker.ts"
compatibility_date = "2000-01-01"
workers_dev = true

send_email = [
    {type = "send_email", name = "SEB", destination_address = "xxx"},
]

[vars]
ALLOWED_ORIGINS = "*"
RECIPIENT_ADDRESS = "*"
SENDER_ADDRESS = "*"
SENDER_NAME = "*"
